FROM golang:1.22

WORKDIR /fase-4-hf-client/src/app

COPY . .

ENV GOPATH=/fase-4-hf-client

RUN go build -ldflags "-w -s" -o bin/hermesfoods cmd/http/main.go

ENTRYPOINT ["./bin/hermesfoods"]

EXPOSE 8080
